### ISSUE TITLE
Memory Issue with large files - greater than roughly 250MB

### ISSUE THREAD

**Issue by jims1103** [chicio/ID3TagEditor#20] opened 2019-09-26 14:07 UTC
Saving tags works flawlessly for files up to at least 217MB, but other files 280MB and larger crash the app with a message of "Terminated due to memory issue".  XCode shows the app consuming over 1.2GB of memory while saving the tags, eventually exhausting the memory and crashing the app.  Seems like a huge memory usage to file size ratio (4:1 or 5:1).

**To Reproduce**
1 - use the sample code from the "Usage" section of this page -> https://github.com/chicio/ID3TagEditor

2 - supply a large MP3 file (at least 300MB, ideally at least 500MB).  Sample files can be found here ->
www.global-sets.com    

For example, this one is 295MB -> 
http://www.global-sets.com/carl-cox-live-ultra-music-festival-miami-united-states-resistance-31-mar-2019/

**Expected behavior**
Expect this to work for MP3 files of all sizes, up to at least 500MB

**Device (please complete the following information):**
 - Model: iPhone6S
 - OS: iOS 12.4.1

**Comment by chicio** [comment] 2019-09-29 10:02
Hi @jims1103 ,

thank you for your issue reporting. 
I will try to have a look at the issue after the completion of the release 3.0.0.
So you need to be patient for a fix 😊. If you want you can submit a PR if you find out the root cause (I suppose a memory leak somewhere).

ps.: support my work by starring my repos 😊

Best regards,
Fabrizio.

**Comment by chicio** [comment] 2019-11-01 10:50
Hi @jims1103 ,
I'm starting to take a look at your issue (now that the version 3.0.0 is out). Seems like the mp3 file doesn't exists. Do you have another example of a big mp3 file?

**Comment by jims1103** [comment] 2019-11-01 11:59
Try this one.  It’s over 600MB.
https://www.edmliveset.com/music/armin-van-buuren-untold-festival-2019-romania/

**Comment by chicio** [comment] 2019-11-02 20:19
Hi @jims1103 ,

I opened a new PR that optimize the memory usage when the mp3 data is written to a file or is returned to the user

#21 **Optimize memory usage on big files**

Basically the following one is the main change 

https://github.com/chicio/ID3TagEditor/pull/21/files?file-filters%5B%5D=.swift#diff-bc27f104c610314bfd5774b9d1f1f3ac

With the removal of the `music` variable there are only two instance of `mp3` data of type `Data` alive at the same time: the original mp3 data and the newly created. Keep in mind that this is the maximum optimization we can achiveve. This means that for example for a mp3 file of over 600 MB you will have a memory usage of 1200 MB (1.2 GB). The only other way to avoid this is modify the `Mp3WithID3TagBuilder` to have in inout parameter (and this is not good). I tested On my iPhone 7 plus the previous implementation and the new one in the PR: the first was crashing (as you told in this issue) and the new one doesn't. Generally speaking (and again as said before) this is the best optimization we can do without breaking or lowering code quality, considering also that file of this size are a limit (and rare) case. I hope anyway that this PR could be helpful. If you want you can start to do a test with the PR branch. I will do a patch release in the following days.

PS Pay attention that the version 3.0.0 of ID3TagEditor is major release with breaking API change. See the readme, the Demos code and the doc https://www.fabrizioduroni.it/ID3TagEditor/ to know how to adapt to this new version.

Best regards,
Fabrizio.

**Comment by BTRLabs** [comment] 2019-11-04 15:33
Thank you for taking the time to look into this.  While this "may" work for 99% of the situations, it's still using WAY more memory than really necessary by reading the entire contents of the file into memory and then writing it back out again (x2).  Look into the following for how to better handle "large" files (in their case, they suggest that being anything large than 1MB, yes, MB).

https://stackoverflow.com/questions/31965566/how-to-efficiently-write-large-files-to-disk-on-background-thread-swift

**Comment by jims1103** [comment] 2019-11-04 15:35
Thank you for taking the time to look into this. While this "may" work for 99% of the situations, it's still using WAY more memory than really necessary by reading the entire contents of the file into memory and then writing it back out again (x2). Look into the following for how to better handle "large" files (in their case, they suggest that being anything large than 1MB, yes, MB).

https://stackoverflow.com/questions/31965566/how-to-efficiently-write-large-files-to-disk-on-background-thread-swift

**Comment by chicio** [comment] 2019-11-12 20:19
Hi @jims1103 , 
this requires too much (really, too much :)) optimization for only a very few cases. I'm closing this because I want to focus on other feature of ID3TagEditor. If you want you can try to do the implementation.

Best regards,
Fabrizio.

**Closed by chicio** 2019-11-12 20:19 UTC

**Comment by jims1103** [comment] 2019-11-13 14:52
@chicio, thanks again for looking into this.  Agreed that this works just fine for 99% of the cases.  In the rare cases that someone is working with larger files, this conversation should serve as the documentation that they need to know what the deal is.
